services:

  backend:
    build:
      context: ./backend

    container_name: parking_backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@database:5432/parking

    depends_on:
      - database


  database:
    image: postgres:16

    container_name: parking_database

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parking

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: